### ISSUE TITLE
Design the landing page of this project

### ISSUE THREAD

**Issue by hasnainmakada-99** [hasnainmakada-99/Open-Source-with-Hasnain#174] opened 2023-09-30 20:09 UTC
**Is your feature request related to a problem? Please describe.**
I would like to request the contributors, if you're from Ui/Ux, then helping us design a landing page and resources page will be of great help since we are deciding to migrate this project from Docsify to react

**Describe the solution you'd like**
You can design the landing page in Figma, photoshop or any software of your choice, but if possible try to do it in figma

**Describe alternatives you've considered**
NaN

**Additional context**
You can reach out to the maintainers on twitter: https://x.com/Hasnain_Makada 

You can provide the design in any format of your choice 😄

**Comment by Akshaya101** [comment] 2023-10-01 23:24
Hello Hasnain, 
I would like to work on this issue, can you please assign this to me?
I wanted to know if you'd want the landing page to be redirected to the website as it is now, and can I also look for other low code tools if they support the cause?

**Comment by hasnainmakada-99** [comment] 2023-10-02 03:46
> Hello Hasnain, I would like to work on this issue, can you please assign this to me? I wanted to know if you'd want the landing page to be redirected to the website as it is now, and can I also look for other low code tools if they support the cause?

Yes akshaya, actually we're going to migrate to Ui soon, so we are right now collecting ideas as of now, so it will be better if you just provide us with how the end design will look like, it should be just the design and no code

Reach me out any further query you have

**Comment by Akshaya101** [comment] 2023-10-02 08:10
Sure! Could you assign this to me?

**Comment by hasnainmakada-99** [comment] 2023-10-02 12:11
Here you go @Akshaya101

**Comment by nishantshukla2884** [comment] 2023-10-02 16:51
can you please assign it to me also @hasnainmakada-99

**Comment by hasnainmakada-99** [comment] 2023-10-03 02:02
Sorry @nishantshukla2884 but @Akshaya101 has raised the concern about this issue first so it will be assigned on a FCFS basis, you can check out other issues or raise one if you have 😄

**Comment by hasnainmakada-99** [comment] 2023-10-12 03:27
Hello @Akshaya101, any updates on this issue?

**Comment by Akshaya101** [comment] 2023-10-12 09:08
Hello @hasnainmakada-99 working on the design, is there a deadline you want to review it by?

**Comment by Gyanendra-Verma** [comment] 2023-10-13 08:35
I want to contribute to this , kindly assign this to me . @hasnainmakada-99

**Comment by hasnainmakada-99** [comment] 2023-10-13 11:46
> Hello @hasnainmakada-99 working on the design, is there a deadline you want to review it by?

There is no deadline @Akshaya101, I was making sure that this issue doesn't go into the stale mode, that's why I asked, but if possible try to complete it Soon

**Comment by hasnainmakada-99** [comment] 2023-10-13 11:47
> I want to contribute to this , kindly assign this to me . @hasnainmakada-99

Sorry brother @Gyanendra-Verma, you can check out other issues to contribute to

**Comment by hasnainmakada-99** [comment] 2023-10-20 11:21
Hey @Akshaya101 any updates on this issue, just checking in with you if there's any problem you might face

**Comment by Akshaya101** [comment] 2023-10-21 13:17
Hi @hasnainmakada-99 done with the landing page, working on the resources part of the page, do you want to have a look? I can send it you on twitter?

**Comment by hasnainmakada-99** [comment] 2023-10-22 06:09
> Hi @hasnainmakada-99 done with the landing page, working on the resources part of the page, do you want to have a look? I can send it you on twitter?

Yeah sure @Akshaya101 or you can put the design here as well

**Comment by Akshaya101** [comment] 2023-10-22 13:11
Hello Hasnain, 
Here is the link to landing page design : https://www.figma.com/file/j6VYXQfJ0oGoHEb1rMk6N1/OSWH?type=design&node-id=72%3A91&mode=design&t=BZQGpECP9YELrw0j-1

**Comment by hasnainmakada-99** [comment] 2023-10-22 15:58
The design looks good @Akshaya101, Great work

**Comment by hasnainmakada-99** [comment] 2023-10-24 12:25
Hey @Akshaya101 , you can now export the design as PNG, then create a new directory inside the root named `designs` and paste the PNG file inside that directory, and then you can raise your PR

**Comment by Akshaya101** [comment] 2023-10-28 14:48
Hey @hasnainmakada-99 should I create separate Folders for `resources` and `home page` under `designs` and put PNG inside that or do you want me to put all of them in under `designs` folder?

**Closed as completed** 2023-11-04 21:03 UTC
Labels: enhancement, help wanted, good first issue, EddieHub:good-first-issue, Designing, hacktoberfest
